Repository Journey-Together/Android, pull requests merged in 2024-05, with the labels that each got.

#21 [Feature]#19 파이어베이스 사용 종료
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/AreaBasedDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/RecentSearchKeywordDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/base/ApiConstants.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/AreaBasedSearchRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/areabased/AreaBasedSearchResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/areabased/Body.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/areabased/Item.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/areabased/Items.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/areabased/Response.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/KorWithService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AreaBasedRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/AreaBasedRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/test/TestActivity.kt
  DaOnGil/app/src/main/res/layout/activity_test.xml
  DaOnGil/build.gradle.kts
Labels: 기능

#29 [#26] 마이페이지 메인 UI
  .idea/.gitignore
  .idea/FinalProject-DaOnGil.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  DaOnGil/app/schemas/kr.tekit.lion.daongil.data.local.MainDataBase/2.json
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/default_profile.xml
  DaOnGil/app/src/main/res/drawable/default_profile.xml
  DaOnGil/app/src/main/res/drawable/ic_chevron_right_24px.xml
  DaOnGil/app/src/main/res/drawable/mypage_profile_background.xml
  DaOnGil/app/src/main/res/layout/dialog_confirm.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#32 [Feature] 응급 지원 메인 UI
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/EmergencyMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/emer_aed_main_icon.xml
  DaOnGil/app/src/main/res/drawable-night/emer_main_background.xml
  DaOnGil/app/src/main/res/drawable-night/pharmacy_main_icon.xml
  DaOnGil/app/src/main/res/drawable/emer_aed_main_icon.xml
  DaOnGil/app/src/main/res/drawable/emer_main_background.xml
  DaOnGil/app/src/main/res/drawable/pharmacy_main_icon.xml
  DaOnGil/app/src/main/res/layout/activity_emergency_map.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_main.xml
Labels: 기능, UI

#31 [#30] 다이얼로그 및 마이페이지 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/res/layout/dialog_confirm.xml
Labels: 리팩토링

#35 [#24] feature 여행 일정 메인화면 UI 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/SchedulePublicAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MainViewModelFactory.kt
  DaOnGil/app/src/main/res/color/color_schedule_d_day.xml
  DaOnGil/app/src/main/res/drawable-night/empty_view.xml
  DaOnGil/app/src/main/res/drawable/empty_view.xml
  DaOnGil/app/src/main/res/drawable/ic_add_24px.xml
  DaOnGil/app/src/main/res/drawable/ic_edit_24.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/app/src/main/res/layout/row_schedule_my.xml
  DaOnGil/app/src/main/res/layout/row_schedule_public.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#37 [#36] 내 일정 공개일정 recyclerview 코드 리팩토링
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/MainActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/SchedulePublicAdapter.kt
Labels: 리팩토링

#39 [#25] feature 온보딩 로그인 화면 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/LoginActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/LoginViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/OnBoardingActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/adapter/OnBoardingViewpagerAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/OnBoardingFirstFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/OnBoardingLastFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/OnBoardingSecondFragment.kt
  DaOnGil/app/src/main/res/drawable-night/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable-night/hearing_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/hearing_select.xml
  DaOnGil/app/src/main/res/drawable-night/infant_family_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/infant_family_select.xml
  DaOnGil/app/src/main/res/drawable-night/onboarding_clover.xml
  DaOnGil/app/src/main/res/drawable-night/physical_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/physical_select.xml
  DaOnGil/app/src/main/res/drawable-night/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/visual_select.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable/hearing_no_select.xml
  DaOnGil/app/src/main/res/drawable/hearing_select.xml
  DaOnGil/app/src/main/res/drawable/image_button_login_kakao.png
  DaOnGil/app/src/main/res/drawable/image_button_login_naver.png
  DaOnGil/app/src/main/res/drawable/infant_family_no_select.xml
  DaOnGil/app/src/main/res/drawable/infant_family_select.xml
  DaOnGil/app/src/main/res/drawable/login_yellow_line.xml
  DaOnGil/app/src/main/res/drawable/onboarding_clover.xml
  DaOnGil/app/src/main/res/drawable/physical_no_select.xml
  DaOnGil/app/src/main/res/drawable/physical_select.xml
  DaOnGil/app/src/main/res/drawable/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable/visual_select.xml
  DaOnGil/app/src/main/res/layout/activity_login.xml
  DaOnGil/app/src/main/res/layout/activity_on_boarding.xml
  DaOnGil/app/src/main/res/layout/fragment_login.xml
  DaOnGil/app/src/main/res/layout/fragment_on_boarding_first.xml
  DaOnGil/app/src/main/res/layout/fragment_on_boarding_last.xml
  DaOnGil/app/src/main/res/layout/fragment_on_boarding_second.xml
  DaOnGil/app/src/main/res/layout/fragment_select_interest.xml
  DaOnGil/app/src/main/res/navigation/login_navigation_graph.xml
Labels: 기능, UI

#41 [#38] 여행일정 메인화면에서 일정 등록하는 기능 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/ScheduleFormActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/res/layout/activity_schedule_form.xml
  DaOnGil/app/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/app/src/main/res/navigation/schedule_form_graph.xml
Labels: 기능, UI

#42 [#28] feature 홈 메인 UI 구현
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/Tourist.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/DisabilityRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeLocationRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeRecommendRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeVPAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/dialog/ModeSettingDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/empty_view_small.xml
  DaOnGil/app/src/main/res/drawable-night/highcontrast_icon.xml
  DaOnGil/app/src/main/res/drawable-night/home_more_icon.xml
  DaOnGil/app/src/main/res/drawable-night/image_mode_setting.png
  DaOnGil/app/src/main/res/drawable-night/location_icon.xml
  DaOnGil/app/src/main/res/drawable/empty_view_small.xml
  DaOnGil/app/src/main/res/drawable/highcontrast_icon.xml
  DaOnGil/app/src/main/res/drawable/home_more_icon.xml
  DaOnGil/app/src/main/res/drawable/image_mode_setting.png
  DaOnGil/app/src/main/res/drawable/indicator_selected.xml
  DaOnGil/app/src/main/res/drawable/indicator_unselected.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp1.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp2.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp3.xml
  DaOnGil/app/src/main/res/drawable/location_icon.xml
  DaOnGil/app/src/main/res/layout/dialog_mode_setting.xml
  DaOnGil/app/src/main/res/layout/fragment_home_main.xml
  DaOnGil/app/src/main/res/layout/item_disability_type.xml
  DaOnGil/app/src/main/res/layout/item_home_vp.xml
  DaOnGil/app/src/main/res/layout/item_tourist_big.xml
  DaOnGil/app/src/main/res/layout/item_tourist_small.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#47 [#33] 응급 지원 상세정보 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMessage.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyMessageAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/AedInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/PharmacyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/EmergencyMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/emergency_message_img.png
  DaOnGil/app/src/main/res/drawable/address_icon.xml
  DaOnGil/app/src/main/res/drawable/aed_pin_icon.xml
  DaOnGil/app/src/main/res/drawable/aed_time_icon.xml
  DaOnGil/app/src/main/res/drawable/call_icon.xml
  DaOnGil/app/src/main/res/drawable/emergency_message_img.png
  DaOnGil/app/src/main/res/drawable/emergency_notice_img.png
  DaOnGil/app/src/main/res/drawable/emergency_radius.xml
  DaOnGil/app/src/main/res/drawable/update_icon.xml
  DaOnGil/app/src/main/res/layout/activity_emergency_info.xml
  DaOnGil/app/src/main/res/layout/activity_emergency_map.xml
  DaOnGil/app/src/main/res/layout/fragment_aed_info.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_info.xml
  DaOnGil/app/src/main/res/layout/fragment_pharmacy_info.xml
  DaOnGil/app/src/main/res/layout/item_emergency_message.xml
  DaOnGil/app/src/main/res/values/styles.xml
Labels: 기능, UI

#49 [#48] androidmanifest activity 설정 오류 및 UI관련 수정
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/hearing_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/visual_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/hearing_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/visual_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/layout/fragment_aed_info.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_info.xml
  DaOnGil/app/src/main/res/layout/fragment_pharmacy_info.xml
Labels: 버그, UI
