Repository Journey-Together/Android, pull requests merged in 2024-06, with the labels that each got.

#50 [#34] 나의 정보 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/MyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/app/src/main/res/drawable/camera_icon.xml
  DaOnGil/app/src/main/res/layout/activity_my_info.xml
  DaOnGil/app/src/main/res/layout/dropdown_item_blood_type.xml
  DaOnGil/app/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/app/src/main/res/navigation/nav_my_info_graph.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#51 [#46] feature 홈 고대비모드 설정
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/HighThemeApp.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/dialog/ModeSettingDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
Labels: 기능

#54 [#44] 마커 테스트, 장애 유형별 옵션 클릭 유지 등등
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/LocalVillageCodeDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/local/dao/VillageCodeDao.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AreaCodeRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/VillageCodeRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/AreaCodeRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/VillageCodeRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/AddVillageCodeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/GetAllDetailAreaCodeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/InitAreaCodeInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/customview/CategoryBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/customview/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/SearchMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/SearchMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/SearchMainViewModelFactory.kt
  DaOnGil/app/src/main/res/drawable-night/chip_elevator_icon.xml
  DaOnGil/app/src/main/res/drawable-night/chip_stroller_icon.xml
  DaOnGil/app/src/main/res/drawable-night/infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable/chip_elevator_icon.xml
  DaOnGil/app/src/main/res/drawable/chip_stroller_icon.xml
  DaOnGil/app/src/main/res/drawable/infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/layout/category_bottom_sheet_layout.xml
  DaOnGil/app/src/main/res/layout/fragment_search_main.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/dimens.xml
  DaOnGil/app/src/main/res/values/strings.xml
  DaOnGil/app/src/main/res/values/styles.xml
Labels: 기능

#53 [#52] 관심 유형 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/ConcernTypeActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/dialog/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/res/layout/activity_concern_type.xml
  DaOnGil/app/src/main/res/layout/fragment_concern_type.xml
  DaOnGil/app/src/main/res/layout/fragment_concern_type_modify.xml
  DaOnGil/app/src/main/res/navigation/nav_concern_type_graph.xml
Labels: 기능, UI

#58 [#55] 최근 검색어 저장 구현 완료
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/RecentSearchKeywordDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/local/RecentSearchKeywordEntity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AreaCodeRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/RecentSearchKeywordRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/RecentSearchKeyword.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/RecentSearchKeywordRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/recent_search_keyword/GetAllRecentSearchKeywordUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/SearchActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/adapter/RecentSearchKeywordAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/vm/SearchViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/vm/SearchViewModelFactory.kt
  DaOnGil/app/src/main/res/drawable-night/x_button_icon.xml
  DaOnGil/app/src/main/res/drawable/ic_close_18px.xml
  DaOnGil/app/src/main/res/drawable/img_no_search_result.gif
  DaOnGil/app/src/main/res/drawable/search_view_background.xml
  DaOnGil/app/src/main/res/drawable/x_button_icon.xml
  DaOnGil/app/src/main/res/layout/activity_search.xml
  DaOnGil/app/src/main/res/layout/row_recent_searched.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#62 [#60] 회원탈퇴 화면 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/ContextExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/Permissions.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/SearchMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/DeleteUserActivity.kt
  DaOnGil/app/src/main/res/layout/activity_delete_user.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
Labels: UI

#61 [#57] 나의 여행지 후기 화면 UI 구현
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/customview/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/MyReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewDetailVPAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/customview/MyReviewDetailBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewDetailFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/res/drawable/delete_icon.xml
  DaOnGil/app/src/main/res/drawable/edit_icon.xml
  DaOnGil/app/src/main/res/drawable/img_2455.JPEG
  DaOnGil/app/src/main/res/drawable/img_2859.JPEG
  DaOnGil/app/src/main/res/drawable/img_8272.JPEG
  DaOnGil/app/src/main/res/drawable/more_vert_icon.xml
  DaOnGil/app/src/main/res/drawable/star_filled_icon.xml
  DaOnGil/app/src/main/res/drawable/star_half_filled_icon.xml
  DaOnGil/app/src/main/res/drawable/star_icon.xml
  DaOnGil/app/src/main/res/layout/activity_my_review.xml
  DaOnGil/app/src/main/res/layout/bottom_sheet_my_review_detail.xml
  DaOnGil/app/src/main/res/layout/fragment_my_review.xml
  DaOnGil/app/src/main/res/layout/fragment_my_review_detail.xml
  DaOnGil/app/src/main/res/layout/item_my_review.xml
  DaOnGil/app/src/main/res/layout/item_my_review_detail_vp.xml
  DaOnGil/app/src/main/res/menu/menu_my_review_detail.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
Labels: 기능, UI

#64 [#56] 응급 지원 지도 UI 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/EmergencyMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/emergency_map_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_selected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_selected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_selected_pharmacy_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_unselected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_unselected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_unselected_pharmacy_icon.xml
  DaOnGil/app/src/main/res/drawable/emergency_map_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_selected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_selected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_selected_pharmacy_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_unselected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_unselected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_unselected_pharmacy_icon.xml
  DaOnGil/app/src/main/res/layout/activity_emergency_map.xml
  DaOnGil/app/src/main/res/layout/emergency_bottom_sheet_layout.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_main.xml
  DaOnGil/app/src/main/res/values-night/themes.xml
  DaOnGil/app/src/main/res/values/strings.xml
  DaOnGil/app/src/main/res/values/styles.xml
Labels: 기능, UI

#67 [#65] 마이페이지 북마크 화면 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlaceBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/ScheduleBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/bookmarkDisabilityRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/decoration/GridSpacingItemDecoration.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/MyReviewActivity.kt
  DaOnGil/app/src/main/res/layout/activity_bookmark.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/item_location_bookmark.xml
  DaOnGil/app/src/main/res/layout/item_schedule_bookmark.xml
Labels: UI

#72 [#63] 관광정보 상세보기 API 테스트 완료
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/HighThemeApp.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDetailInfoDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceDetailInfoRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceDetailInfoRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetPlaceDetailInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/test/TestActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/test/vm/TestViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/test/vm/TestViewModelFactory.kt
Labels: 기능

#71 [#66] 응급 지원 바텀 시트 세부 화면 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBottom.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyBottomAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/res/drawable/address_icon.xml
  DaOnGil/app/src/main/res/drawable/call_icon.xml
  DaOnGil/app/src/main/res/drawable/emergency_bed_icon.xml
  DaOnGil/app/src/main/res/drawable/emergency_radius.xml
  DaOnGil/app/src/main/res/layout/emergency_bottom_sheet_layout.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_info.xml
  DaOnGil/app/src/main/res/layout/item_emergency_bottom.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#76 [#75] 검색화면 장애 유형 선택 버튼 중복 클릭 방지 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/TokenRefreshAuthenticator.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/FlowExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/ViewExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/SearchMainFragment.kt
Labels: 기능

#77 [#43] 카카오 O-Auth 로그인 구현
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/LoginDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/login/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/login/UserLoginResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/LoginService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/UserLoginRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/UserInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/UserLoginRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/UserLoginUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/LoginViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/OnBoardingActivity.kt
  DaOnGil/gradle.properties
  DaOnGil/gradle/wrapper/gradle-wrapper.properties
  DaOnGil/settings.gradle.kts
Labels: 기능

#79 [#74] 응급지원 지도 지역 설정 다이얼로그 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyAreaDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModelFactory.kt
  DaOnGil/app/src/main/res/color/color_button_emergency_area.xml
  DaOnGil/app/src/main/res/color/color_text_emergency_area.xml
  DaOnGil/app/src/main/res/layout/dialog_emergency_area.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/arrays.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#86 [#80] 응급 지원 지도 버튼 현위치와 연결
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/HighThemeApp.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/NaverMapDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Area0.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Center.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Code.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Coords.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Region.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Result.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/ReverseGecodeResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/naverMap/Status.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/NaverMapService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/NaverMapRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReverseGecode.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/NaverMapRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetUserLocationRegionUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
Labels: 기능, UI

#83 [#73] 사용자 인증 토큰, 유저정보 Data Source 저장
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/HighThemeApp.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/AuthDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/TokenDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/local/UserResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/login/UserLoginResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/signin/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/signin/SignInResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/local/AppSettings.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/local/DataStore.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/AuthAuthenticator.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/AuthInterceptor.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/TokenRefreshAuthenticator.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/AuthService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/LoginService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AuthRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/UserLoginRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/User.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/UserInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/AuthRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceDetailInfoRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/UserLoginRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetMyInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/SignInUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/UserLoginUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/LoginActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/UiState.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/SplashFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/LoginViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/LoginViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/SplashViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/SplashViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_splash.xml
  DaOnGil/app/src/main/res/navigation/login_navigation_graph.xml
  DaOnGil/build.gradle.kts
Labels: 기능

#89 [#84] 관광지 후기 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/WriteReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewListRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/WriteReviewImageRVAdapter.kt
  DaOnGil/app/src/main/res/drawable-night/add_image_icon.xml
  DaOnGil/app/src/main/res/drawable-night/cancel_icon.xml
  DaOnGil/app/src/main/res/drawable-night/emergency_icon.xml
  DaOnGil/app/src/main/res/drawable/add_image_icon.xml
  DaOnGil/app/src/main/res/drawable/cancel_icon.xml
  DaOnGil/app/src/main/res/drawable/emergency_icon.xml
  DaOnGil/app/src/main/res/layout/activity_review_list.xml
  DaOnGil/app/src/main/res/layout/activity_write_review.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_big.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_small.xml
  DaOnGil/app/src/main/res/layout/item_review_big_image.xml
  DaOnGil/app/src/main/res/layout/item_review_write_image.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#90 [#78] 네이버 O-Auth 로그인 구현
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/SelectInterestFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/OnBoardingLastFragment.kt
  DaOnGil/app/src/main/res/drawable-night/background_rectangle.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable-night/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/visual_select.xml
  DaOnGil/app/src/main/res/drawable/background_rectangle.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable/image_button_login_kakao.png
  DaOnGil/app/src/main/res/drawable/image_button_login_naver.png
  DaOnGil/app/src/main/res/drawable/kakao_login.xml
  DaOnGil/app/src/main/res/drawable/login_yellow_line2.xml
  DaOnGil/app/src/main/res/drawable/naver_login.xml
  DaOnGil/app/src/main/res/drawable/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable/visual_select.xml
  DaOnGil/app/src/main/res/layout/fragment_login.xml
  DaOnGil/app/src/main/res/layout/fragment_on_boarding_last.xml
  DaOnGil/app/src/main/res/layout/fragment_select_interest.xml
  DaOnGil/app/src/main/res/navigation/login_navigation_graph.xml
Labels: 기능, UI, 리팩토링

#97 [#87] 응급실 지도 api 연결
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/EmergencyDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/Body.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/EmergencyBasicResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/Header.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/Item.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/Items.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/Response.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/Body.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/EmergencyRealtime.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/EmergencyRealtimeJsonAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/EmergencyRealtimeResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/Header.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/Item.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/Items.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/Response.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/EmergencyService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/EmergencyRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBasicInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBottom.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyRealtimeInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/EmergencyRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetEmergencyMapInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyBottomAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_emergency_map.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_main.xml
  DaOnGil/app/src/main/res/layout/item_emergency_bottom.xml
  DaOnGil/app/src/main/res/values/arrays.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#99 [#96] 후기 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/res/drawable-night/review_star_icon.xml
  DaOnGil/app/src/main/res/drawable/review_star_background.xml
  DaOnGil/app/src/main/res/drawable/review_star_icon.xml
  DaOnGil/app/src/main/res/layout/activity_detail.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_small.xml
Labels: UI, 리팩토링

#102 [#85] 마이페이지 기본 정보
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/bookmarkDisabilityRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/decoration/GridSpacingItemDecoration.kt
  DaOnGil/app/src/main/res/layout/activity_bookmark.xml
  DaOnGil/app/src/main/res/layout/fragment_concern_type_modify.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/item_bookmark_disabiltiy_type.xml
  DaOnGil/app/src/main/res/layout/item_location_bookmark.xml
  DaOnGil/app/src/main/res/layout/item_schedule_bookmark.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: UI

#100 [#69] 작성된 여행 일정을 보는 화면 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailyPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/SchedulePlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/ScheduleImageViewPagerAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/ScheduleListAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/SchedulePlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ReviewReportDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ScheduleManageBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ScheduleReviewManageBottomSheet.kt
  DaOnGil/app/src/main/res/drawable-night/empty_view.xml
  DaOnGil/app/src/main/res/drawable-night/empty_view_small.xml
  DaOnGil/app/src/main/res/drawable/bookmark_filled_icon.xml
  DaOnGil/app/src/main/res/drawable/empty_view.xml
  DaOnGil/app/src/main/res/drawable/empty_view_small.xml
  DaOnGil/app/src/main/res/drawable/icon_lock.xml
  DaOnGil/app/src/main/res/drawable/icon_lock_open.xml
  DaOnGil/app/src/main/res/drawable/shape_schedule_image_overlay.xml
  DaOnGil/app/src/main/res/layout/activity_schedule.xml
  DaOnGil/app/src/main/res/layout/bottom_sheet_schedule_manage.xml
  DaOnGil/app/src/main/res/layout/bottom_sheet_schedule_review_manage.xml
  DaOnGil/app/src/main/res/layout/dialog_review_report.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/app/src/main/res/layout/item_schedule_empty.xml
  DaOnGil/app/src/main/res/layout/item_schedule_image.xml
  DaOnGil/app/src/main/res/layout/item_schedule_list.xml
  DaOnGil/app/src/main/res/layout/item_schedule_place.xml
  DaOnGil/app/src/main/res/layout/row_schedule_my.xml
  DaOnGil/app/src/main/res/menu/menu_schedule_private.xml
  DaOnGil/app/src/main/res/menu/menu_schedule_public.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#105 [#98] aed api 지도와 연결
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/AedDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/AedJsonAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/AedResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/Body.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/Header.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/Item.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/Items.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/Response.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/EmergencyRealtime.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/AedService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AedRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/AedMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBottom.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/AedRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetAedMapInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetEmergencyMapInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyBottomAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyAreaDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/EmergencyMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/aed_bottom_img.xml
  DaOnGil/app/src/main/res/drawable-night/emergency_bottom_img.xml
  DaOnGil/app/src/main/res/drawable-night/marker_selected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_selected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_unselected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable-night/marker_unselected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable-night/pharmacy_bottom_img.xml
  DaOnGil/app/src/main/res/drawable/aed_bottom_img.xml
  DaOnGil/app/src/main/res/drawable/emergency_bottom_img.xml
  DaOnGil/app/src/main/res/drawable/marker_selected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_selected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_unselected_aed_icon.xml
  DaOnGil/app/src/main/res/drawable/marker_unselected_emergency_icon.xml
  DaOnGil/app/src/main/res/drawable/pharmacy_bottom_img.xml
  DaOnGil/app/src/main/res/layout/emergency_bottom_sheet_layout.xml
  DaOnGil/app/src/main/res/layout/item_emergency_bottom.xml
  DaOnGil/app/src/main/res/values/arrays.xml
Labels: 기능, UI

#107 [#106] aed 상세보기 구현 응급실 상세보기 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/aed/AedResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/basic/EmergencyBasicResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/realtime/EmergencyRealtimeResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/AedMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBottom.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/AedInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyInfoFragment.kt
  DaOnGil/app/src/main/res/layout/fragment_aed_info.xml
  DaOnGil/app/src/main/res/layout/fragment_emergency_info.xml
Labels: 기능, UI

#111 [#108] 응급실 이용 안내 실시간 메세지 기능 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/EmergencyDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/Body.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/EmergencyMessageJsonAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/EmergencyMessageResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/Header.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/Item.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/Items.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/emergency/message/Response.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/EmergencyService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/EmergencyRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMessage.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMessageInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/EmergencyRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetEmergencyMessageUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyMessageAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyInfoViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_emergency_info.xml
Labels: 기능, UI

#112 [#103] 나의 여행지 후기 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewModifyImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/customview/MyReviewDetailBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewDetailFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/fragment_my_review_detail.xml
  DaOnGil/app/src/main/res/layout/fragment_my_review_modify.xml
  DaOnGil/app/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/app/src/main/res/layout/item_my_review.xml
  DaOnGil/app/src/main/res/layout/item_schedule_bookmark.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
Labels: 기능, UI

#68 [#45] 일정 작성화면 UI 구현
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/BookmarkedPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailySchedule.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/FormPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/FormSearchedPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/ScheduleFormActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/res/drawable/edittext_background.xml
  DaOnGil/app/src/main/res/layout/activity_schedule_form.xml
  DaOnGil/app/src/main/res/layout/fragment_form_search.xml
  DaOnGil/app/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/app/src/main/res/layout/item_form_bookmarked_places.xml
  DaOnGil/app/src/main/res/layout/item_form_place.xml
  DaOnGil/app/src/main/res/layout/item_form_schedule.xml
  DaOnGil/app/src/main/res/layout/item_form_search_result.xml
  DaOnGil/app/src/main/res/navigation/schedule_form_graph.xml
  DaOnGil/app/src/main/res/values/strings.xml
  DaOnGil/app/src/main/res/values/styles.xml
Labels: UI

#122 [#115] 여행일정 후기 작성 화면 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/customview/ReviewPublicDialog.kt
  DaOnGil/app/src/main/res/layout/activity_write_schedule_review.xml
  DaOnGil/app/src/main/res/layout/dialog_review_public.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: UI

#125 [#88] 사용자 정보개인정보응급정보 api
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/MemberDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/base/AdapterProvider.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/MyIceInfoRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/MyPersonalInfoRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/MyProfileImgRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/MyDefaultInfoData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/MyDefaultInfoResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/MyInfoData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/MyInfoResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/MemberService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/MemberRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/IceInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyDefaultInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PersonalInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ProfileImg.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/MemberRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetMyDefaultInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetMyInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/ModifyMyIceInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/ModifyMyPersonalInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/ModifyMyProfileImageUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/BitmapExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/ContextExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/StringExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/UriExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/LogInState.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/UiState.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/SplashFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/SplashViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/MainActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MainViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MyInfoMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/MyInfoMainViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/ModifyState.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/MyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/vm/MyInfoViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_concern_type_modify.xml
  DaOnGil/app/src/main/res/layout/fragment_ice_modify.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info.xml
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/fragment_personal_info_modify.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능

#126 [Feat] #121 네이버 로그인 토큰 저장 완료
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/HighThemeApp.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/LoginFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/DeleteUserActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/vm/SplashViewModel.kt
Labels: 기능

#128 [#119] 응급실 aed 지도 지역 카메라 이동 버그
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyBottom.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/EmergencyMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/HospitalMapInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetEmergencyMapInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetHospitalMapInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/PharmacyMapActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/adapter/EmergencyBottomAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/AedInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/PharmacyBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyMapViewModelFactory.kt
Labels: 기능, UI

#133 [Feat] 사용자 프로필 이미지 수정 완료
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
Labels: 기능

#131 [#118] 북마크한 여행지 리스트 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceBookmarkDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanBookmarkDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/bookmark/PlaceBookmarkData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/bookmark/PlaceBookmarkResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/bookmark/PlanBookmarkData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/bookmark/PlanBookmarkResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/BookmarkService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceBookmarkRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanBookmarkRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlanBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceBookmarkRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanBookmarkRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetPlaceBookmarkUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetPlanBookmarkUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlaceBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlanBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/ScheduleBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/bookmarkDisabilityRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/vm/BookmarkViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/vm/BookmarkViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_bookmark.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#135 [#130] 홈 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/WriteReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/res/layout/activity_write_review.xml
  DaOnGil/app/src/main/res/layout/fragment_home_main.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_small.xml
  DaOnGil/app/src/main/res/layout/item_tourist_small.xml
Labels: 기능, UI, 리팩토링

#140 [#139]고대비 테마 적용시 액티비티 재시작 버그 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/dialog/ModeSettingDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/OnBoardingActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/SplashActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/OnBoardingFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/fragment/SplashFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/vm/SplashViewModel.kt
  DaOnGil/app/src/main/res/layout/activity_on_boarding.xml
  DaOnGil/app/src/main/res/layout/activity_splash.xml
  DaOnGil/app/src/main/res/layout/fragment_splash.xml
Labels: 버그

#143 [#142] local database 지역 이름으로 지역코드 가져오기
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/LocalVillageCodeDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/areacode/LocalAreaCodeDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/local/dao/AreaCodeDao.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/local/dao/VillageCodeDao.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/AreaCodeRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/VillageCodeRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/AreaCodeRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/VillageCodeRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/AddVillageCodeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/GetAllVillageCodeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/GetAreaCodeByNameUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/GetAreaCodeInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/GetVillageCodeByNameUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/areacode/InitAreaCodeInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/GetMyInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/ModifyMyIceInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/ModifyMyPersonalInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/ModifyMyProfileImageUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/searchkeyword/SearchByKeywordUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/HomeViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/HomeViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/SearchMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/SearchMainViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/vm/MyInfoViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/vm/SplashViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/vm/SearchViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/search/vm/SearchViewModelFactory.kt
Labels: 기능

#146 [#145] feature 홈 메인화면 api 지역코드 전달
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/HomeViewModel.kt
Labels: 기능

#149 [#136] 여행일정 메인화면에 공개일정 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/OpenPlanListResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/OpenPlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/OpenPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/OpenPlanInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetOpenPlanListUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/GlideExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/SchedulePublicAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModelFactory.kt
Labels: 기능, UI

#138 [#123] 일정 작성화면 코드 개선
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/ScheduleFormActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/res/layout/activity_schedule_form.xml
  DaOnGil/app/src/main/res/layout/fragment_form_search.xml
  DaOnGil/app/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/app/src/main/res/layout/item_form_place.xml
  DaOnGil/app/src/main/res/layout/item_form_schedule.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: UI, 리팩토링

#151 [#147] 마이페이지 메인화면 비회원/회원 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#155 [#153] 스플래시 스크린 구현
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/base/ApiConstants.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/SplashActivity.kt
  DaOnGil/app/src/main/res/layout/activity_splash.xml
  DaOnGil/app/src/main/res/raw/splash_video.mp4
  DaOnGil/app/src/main/res/values-night/themes.xml
  DaOnGil/app/src/main/res/values/themes.xml
Labels: 기능, UI

#156 [#154] 여행 일정 북마크 api 연결 및 UI 설정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/BookmarkDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/bookmark/PlanBookmarkData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/BookmarkService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/BookmarkRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlanBookmark.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/BookmarkRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/UpdatePlanBookmarkUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlaceBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlanBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/vm/BookmarkViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/vm/BookmarkViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/item_location_bookmark.xml
  DaOnGil/app/src/main/res/layout/item_schedule_bookmark.xml
Labels: 기능

#161 [#159] 공개일정 더보기 페이지 API 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/OpenPlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/OpenPlanInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PublicSchedule.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/PublicScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/adapter/PublicScheduleAdpater.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/vm/PublicScheduleViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/vm/PublicScheduleViewModelFactory.kt
Labels: 기능, UI

#168 [#150] 여행 일정 작성 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/DailyPlaceRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/NewPlanRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/PlaceSearchInfoData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/PlaceSearchResultsData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/PlaceSearchResultsResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/BookmarkedPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailyPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailySchedule.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/FormPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/NewPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceSearchInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceSearchResult.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/AddNewPlanUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetPlaceSearchResultUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/ScheduleFormActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_form_search.xml
  DaOnGil/app/src/main/res/layout/fragment_schedule_details_form.xml
  DaOnGil/app/src/main/res/layout/item_form_search_result.xml
Labels: 기능

#172 [#167] 내 일정 보기 api 메인 화면 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myMainSchedule/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myMainSchedule/MyMainScheduleResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/openSchedule/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/openSchedule/OpenPlanListResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/openSchedule/OpenPlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyMainSchedule.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetMyMainScheduleUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/onboarding/SplashActivity.kt
  DaOnGil/app/src/main/res/layout/fragment_schedule_main.xml
  DaOnGil/app/src/main/res/layout/row_schedule_public.xml
Labels: 기능, UI

#173 [#170] 여행 일정 나의 북마크 장소 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_form_search.xml
  DaOnGil/app/src/main/res/layout/item_form_place.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#175 [#165] 마이페이지 테스트
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/MemberDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/ConcernTypeRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/ConcernTypeData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/ConcernTypeResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/MemberService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/MemberRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ConcernType.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/MemberRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/GetConcernTypeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/UpdateConcernTypeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/vm/ConcernTypeViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/vm/ConcernTypeViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewDetailVPAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewDetailFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/app/src/main/res/layout/fragment_my_review_modify.xml
Labels: 기능, UI

#176 [#164] 홈 테스트 이슈
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/DetailPlaceGuestResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/SubDisabilityGuestRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/SubDisabilityRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfoGuest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/SubDisability.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/WriteReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailInfoRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewListRVAdapter.kt
  DaOnGil/app/src/main/res/layout/activity_detail.xml
Labels: 리팩토링

#182 [#181] 관광지 상세보기 response 데이터 구조 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/DetailPlaceGuestResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/SubDisabilityGuestRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/SubDisabilityRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfoGuest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/SubDisability.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailInfoRVAdapter.kt
Labels: 리팩토링

#186 [#185] emergencyinfo 관련 리팩토링
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/EmergencyInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/fragment/EmergencyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/emergency/vm/EmergencyInfoViewModelFactory.kt
Labels: 리팩토링

#191 [#190] 마이페이지 관심 유형 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/MemberDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/ConcernTypeRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/ConcernTypeData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/member/ConcernTypeResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/MemberService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/MemberRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ConcernType.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/MemberRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/GetConcernTypeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/myinfo/UpdateConcernTypeUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/vm/ConcernTypeViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/vm/ConcernTypeViewModelFactory.kt
Labels: 기능

#194 [#187] 관광지 후기 모아보기 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/placeReview/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/placeReview/MyPlaceReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/placeReview/PlaceReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfoGuest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceReviewInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/GetPlaceReviewListUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/ContextExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewListRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/vm/ReviewListViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/vm/ReviewListViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/ConfirmDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/DeleteUserActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
Labels: 기능

#195 [#193] 나의 여행지 후기 목록보기 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/review/MyPlaceReviewData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/review/MyPlaceReviewDto.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/review/MyPlaceReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyPlaceReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/GetMyPlaceReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_my_review.xml
  DaOnGil/app/src/main/res/layout/item_my_review.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능

#196 [#192] 일정 작성 기능 추가 및 변경
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/NewPlanRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/NewPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormBookmarkedPlacesAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
Labels: 기능, 리팩토링

#201 [#200] confirmdialog 오류
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
Labels: 버그

#205 [#204] 신고하기 화면 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/report/ReportActivity.kt
  DaOnGil/app/src/main/res/layout/activity_report.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI
