Repository Journey-Together/Android, pull requests merged in 2024-07, with the labels that each got.

#207 [#203] 관광정보 후기 작성 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/PlaceReviewDataRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/PlaceReviewImageRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/ReviewGuestRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/ReviewRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/LocalDateAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/RetrofitInstance.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/NewReviewData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/NewReviewImages.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/Review.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/WritePlaceReviewDataUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/WriteReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/WriteReviewImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/vm/WriteReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/vm/WriteReviewViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/res/layout/activity_detail.xml
  DaOnGil/app/src/main/res/layout/activity_write_review.xml
Labels: 기능, UI

#210 [#202] 나의 여행지 후기 자세히 보기 삭제 및 기타 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/myreview/MyPlaceReviewData.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/myreview/MyPlaceReviewDto.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/myreview/MyPlaceReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewDetailVPAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/customview/MyReviewDetailBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewDetailFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/res/layout/fragment_my_review_detail.xml
  DaOnGil/app/src/main/res/layout/item_my_review_detail_vp.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
Labels: 기능

#208 [#197] 여행 일정 후기 작성 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/ScheduleReviewRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/briefScheduleInfo/BriefScheduleInfoResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/briefScheduleInfo/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/BriefScheduleInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/NewScheduleReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewImg.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/AddNewScheduleReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetBriefScheduleInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/adapter/WriteReviewImageAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/customview/ReviewPublicDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/vm/WriteScheduleReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/vm/WriteScheduleReviewViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_write_schedule_review.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능

#215 [#214] 나의 여행지 리뷰 상세보기 관련 코드 삭제
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewModifyFragment.kt
Labels: 버그

#213 [#209] 일정 작성 여행지 검색 목록 페이징
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormPlaceAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormScheduleAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/adapter/FormSearchResultAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/NameAndPeriodFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleDetailsFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/res/layout/fragment_form_search.xml
  DaOnGil/app/src/main/res/layout/fragment_name_and_period_form.xml
  DaOnGil/app/src/main/res/layout/item_form_place.xml
Labels: 기능

#222 [#217] 일정 후기 수정 UI 구현
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewImage.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/adapter/ModifyReviewImageAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
  DaOnGil/app/src/main/res/drawable-night/review_image_icon.xml
  DaOnGil/app/src/main/res/drawable/dotted_line_horizontal.xml
  DaOnGil/app/src/main/res/drawable/review_image_icon.xml
  DaOnGil/app/src/main/res/drawable/selector_review_public_background.xml
  DaOnGil/app/src/main/res/drawable/selector_review_public_text.xml
  DaOnGil/app/src/main/res/layout/activity_modify_schedule_review.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: UI

#221 [#212] 관광정보 후기목록 보기 페이징 처리
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/ReviewGuestRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/ReviewRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/Review.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/vm/ReviewListViewModel.kt
  DaOnGil/app/src/main/res/layout/activity_review_list.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_small.xml
Labels: 기능, UI

#223 [#216] 일정 후기 유효성 검사 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/customview/ReviewPublicDialog.kt
  DaOnGil/app/src/main/res/layout/activity_modify_schedule_review.xml
  DaOnGil/app/src/main/res/layout/activity_write_schedule_review.xml
  DaOnGil/app/src/main/res/layout/dialog_review_public.xml
Labels: 기능, UI

#229 [#227] 관광정보 상세보기 후기 버튼 설정 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/mainplace/AroundPlaceRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/mainplace/RecommendPlaceRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/searchplace/list/PlaceRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/AroundPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/RecommendPlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/res/layout/activity_detail.xml
Labels: 기능, UI

#226 [#220] 나의 여행지 후기 삭제 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/myreview/MyPlaceReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/DeleteMyPlaceReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModelFactory.kt
Labels: 기능

#228 [#218] 일정 상세보기 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailyPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/ScheduleListAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/SchedulePlaceAdapter.kt
  DaOnGil/app/src/main/res/color/color_text_emergency_area.xml
  DaOnGil/app/src/main/res/drawable-night/report_button.xml
  DaOnGil/app/src/main/res/drawable-night/right_icon.xml
  DaOnGil/app/src/main/res/drawable-night/schedule_detail_elderly.xml
  DaOnGil/app/src/main/res/drawable-night/schedule_detail_hearing_impaired.xml
  DaOnGil/app/src/main/res/drawable-night/schedule_detail_infant_family.xml
  DaOnGil/app/src/main/res/drawable-night/schedule_detail_physical_disability.xml
  DaOnGil/app/src/main/res/drawable-night/schedule_detail_visual_impairment.xml
  DaOnGil/app/src/main/res/drawable/more_vert_icon.xml
  DaOnGil/app/src/main/res/drawable/report_button.xml
  DaOnGil/app/src/main/res/drawable/right_icon.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_elderly.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_hearing_impaired.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_infant_family.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_physical_disability.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_visual_impairment.xml
  DaOnGil/app/src/main/res/layout/activity_schedule.xml
  DaOnGil/app/src/main/res/layout/item_schedule_empty.xml
  DaOnGil/app/src/main/res/layout/item_schedule_list.xml
  DaOnGil/app/src/main/res/layout/item_schedule_place.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#231 [#230] 관광정보 상세보기 데이터 추가
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/DetailPlaceGuestResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceDetailInfoGuest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/GetPlaceDetailInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/res/layout/activity_detail.xml
Labels: 기능, UI

#237 [#232] 일정 상세보기 api 연결
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/openSchedule/OpenPlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/Daily.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/DailyPlaceInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/ScheduleDetailResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/DailyPlan.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/OpenPlanInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetail.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/SchedulePlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetMyMainScheduleUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailInfoGuestUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/PublicScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleDetailInfoActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/adapter/ScheduleListAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailInfoViewModelFactory.kt
  DaOnGil/app/src/main/res/drawable/bookmark_fill_scheduledetail_icon.xml
  DaOnGil/app/src/main/res/drawable/bookmark_schedule_detail_icon.xml
  DaOnGil/app/src/main/res/drawable/schedule_detail_basic_img.xml
  DaOnGil/app/src/main/res/layout/activity_schedule.xml
  DaOnGil/app/src/main/res/layout/item_schedule_image.xml
  DaOnGil/app/src/main/res/layout/item_schedule_place.xml
  DaOnGil/app/src/main/res/menu/menu_schedule_public.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#236 [#225] 나의 여행지 후기 수정 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlaceDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/MyPlaceReivewImgRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/MyPlaceReviewRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlaceService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlaceRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyPlaceReviewImages.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyPlaceReviewInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/UpdateMyPlaceReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlaceRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/UpdateMyPlaceReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewModifyImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_report.xml
  DaOnGil/app/src/main/res/layout/fragment_my_review_modify.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: 기능, UI

#240 [#238] 관심 유형 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_selected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable-night/sv_unselected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable-night/visual_select.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_no_select.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_select.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_selected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable/sv_unselected_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/visual_no_select.xml
  DaOnGil/app/src/main/res/drawable/visual_select.xml
  DaOnGil/app/src/main/res/layout/fragment_concern_type.xml
Labels: UI, 리팩토링

#233 [#224] 일정 메인화면과 관련된 기능 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleElapsed/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleElapsed/MyElapsedResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleElapsed/PlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleUpcoming/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleUpcoming/MyUpcomingsResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/myScheduleUpcoming/PlanRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyElapsedScheduleInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyElapsedSchedules.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyUpcomingScheduleInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/MyUpcomingSchedules.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetMyElapsedSchedulesUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetMyUpcomingSchedulesUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/adapter/MyScheduleElapsedAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/adapter/MyScheduleUpcomingAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/vm/MyScheduleViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/vm/MyScheduleViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/item_my_schedule_elapsed.xml
  DaOnGil/app/src/main/res/layout/row_schedule_my.xml
Labels: 기능

#244 [#243] 일정 상세 화면 Activity명 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/MyScheduleActivity.kt
Labels: 버그

#246 [#242] 마이페이지 뒤로 가기 설정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/concerntype/fragment/ConcernTypeModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/IceModifyFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/PersonalInfoModifyFragment.kt
  DaOnGil/app/src/main/res/navigation/nav_concern_type_graph.xml
  DaOnGil/app/src/main/res/navigation/nav_my_info_graph.xml
  DaOnGil/app/src/main/res/navigation/nav_my_review_graph.xml
Labels: 버그

#249 [#239] 일정 상세보기 리뷰 관련 작업
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/ScheduleDetailReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/ScheduleDetailResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetailReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetailnfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/DeleteMyPlanReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailGuestUsecase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailInfoGuestUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailInfoUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/ScheduleMyAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myschedule/MyScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/PublicScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ScheduleReviewManageBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailInfoViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_schedule.xml
Labels: 기능, UI

#250 [#247] 마이페이지 북마크 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlaceBookmarkRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/adapter/PlanBookmarkRVAdapter.kt
  DaOnGil/app/src/main/res/drawable-night/bookmark_fill_icon.xml
  DaOnGil/app/src/main/res/drawable-night/bookmark_icon.xml
  DaOnGil/app/src/main/res/drawable-night/elderly_people_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/empty_view_long.xml
  DaOnGil/app/src/main/res/drawable-night/hearing_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/infant_familly_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/physical_disability_radius_icon.xml
  DaOnGil/app/src/main/res/drawable-night/visual_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/bookmark_fill_icon.xml
  DaOnGil/app/src/main/res/drawable/bookmark_icon.xml
  DaOnGil/app/src/main/res/drawable/elderly_people_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/empty_view_long.xml
  DaOnGil/app/src/main/res/drawable/hearing_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/infant_familly_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/item_gradation.xml
  DaOnGil/app/src/main/res/drawable/physical_disability_radius_icon.xml
  DaOnGil/app/src/main/res/drawable/visual_impairment_radius_icon.xml
  DaOnGil/app/src/main/res/layout/activity_bookmark.xml
  DaOnGil/app/src/main/res/layout/item_bookmark_disabiltiy_type.xml
  DaOnGil/app/src/main/res/layout/item_location_bookmark.xml
  DaOnGil/app/src/main/res/layout/item_schedule_bookmark.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: UI, 리팩토링

#254 [#253] 일정 상세보기 이동 오류
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/bookmark/BookmarkActivity.kt
Labels: 버그
