Repository Journey-Together/Android, pull requests merged in 2024-08, with the labels that each got.

#256 [#252] 마이페이지 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/MyInfoMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/fragment/MyInfoFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myinfo/vm/MyInfoViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/fragment/MyReviewFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/vm/MyReviewViewModel.kt
  DaOnGil/app/src/main/res/layout/fragment_my_info_main.xml
  DaOnGil/app/src/main/res/layout/item_review_big_image.xml
Labels: 리팩토링

#255 [#251] 본인 일정 상세보기 관련 기능 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/ScheduleDetailResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleDetailInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/DeleteMyPlanScheduleUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailGuestUsecase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleDetailUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/UpdateMyPlanPublicUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ResultCode.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ScheduleManageBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/customview/ScheduleReviewManageBottomSheet.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/vm/ScheduleDetailViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#257 [#248] 여행일정 수정 UI, API 연결
  DaOnGil/app/src/main/AndroidManifest.xml
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/plan/scheduleDetail/DailyPlaceInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/SchedulePlace.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/place/GetPlaceSearchResultUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/ModifyScheduleUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/SnackbarExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/ModifyScheduleFormActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/FormSearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ModifyNamePeriodFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ModifyScheduleConfirmFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ModifyScheduleDetailsFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ModifySearchFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ModifyScheduleFormViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ModifyScheduleFormViewModelFactory.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ScheduleFormViewModel.kt
  DaOnGil/app/src/main/res/layout/activity_modify_schedule_form.xml
  DaOnGil/app/src/main/res/layout/fragment_modify_name_period.xml
  DaOnGil/app/src/main/res/layout/fragment_modify_schedule_confirm.xml
  DaOnGil/app/src/main/res/layout/fragment_modify_schedule_details.xml
  DaOnGil/app/src/main/res/layout/fragment_modify_search.xml
  DaOnGil/app/src/main/res/navigation/modify_schedule_form_graph.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#263 [#262] usecase 이름 변경으로 인한 오류 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedule/ScheduleDetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/fragment/ScheduleConfirmFormFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ModifyScheduleFormViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/scheduleform/vm/ModifyScheduleFormViewModelFactory.kt
Labels: 버그, 기능

#264 [#235] 홈 메인화면 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/dpToPxExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/ItemDeco/ItemOffsetDecoration.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeLocationRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeRecommendRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/adapter/HomeVPAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/customview/CustomPageIndicator.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/highcontrast_icon.xml
  DaOnGil/app/src/main/res/drawable-night/home_search_banner.xml
  DaOnGil/app/src/main/res/drawable-night/item_gradation_big.xml
  DaOnGil/app/src/main/res/drawable-night/item_home_vp1.xml
  DaOnGil/app/src/main/res/drawable-night/item_home_vp2.xml
  DaOnGil/app/src/main/res/drawable-night/item_home_vp3.xml
  DaOnGil/app/src/main/res/drawable-night/item_vp_count_background.xml
  DaOnGil/app/src/main/res/drawable/highcontrast_icon.xml
  DaOnGil/app/src/main/res/drawable/home_search_banner.xml
  DaOnGil/app/src/main/res/drawable/indicator_unselected.xml
  DaOnGil/app/src/main/res/drawable/item_gradation_big.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp1.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp2.xml
  DaOnGil/app/src/main/res/drawable/item_home_vp3.xml
  DaOnGil/app/src/main/res/drawable/item_vp_count_background.xml
  DaOnGil/app/src/main/res/layout/fragment_home_main.xml
  DaOnGil/app/src/main/res/layout/item_home_vp.xml
  DaOnGil/app/src/main/res/layout/item_tourist_big.xml
  DaOnGil/app/src/main/res/layout/item_tourist_location.xml
  DaOnGil/app/src/main/res/layout/item_tourist_recommend.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/styles.xml
Labels: UI, 리팩토링

#260 [#258] 이미지 보기 기능
  DaOnGil/app/build.gradle.kts
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/ContextExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/PhotoDialog.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/MyReviewImageRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/myreview/adapter/PhotoVPAdapter.kt
  DaOnGil/app/src/main/res/layout/dialog_photo.xml
  DaOnGil/app/src/main/res/layout/item_photo_vp.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
  DaOnGil/app/src/main/res/values/strings.xml
Labels: 기능, UI

#261 [#259] 공개 일정 페이징
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/ext/RvExt.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/ScheduleMainFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/vm/ScheduleMainViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/PublicScheduleActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/adapter/PublicScheduleAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/publicschedule/vm/PublicScheduleViewModel.kt
Labels: 기능, UI

#265 [#245] 여행 일정 후기 수정 api 연결
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/datasource/PlanDataSource.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/request/ModifyScheduleReviewRequest.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/network/service/PlanService.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ModifiedScheduleReview.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ReviewImage.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/ScheduleReviewInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/GetScheduleReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/usecase/plan/ModifyScheduleReviewUseCase.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/ModifyScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/adapter/ModifyReviewImageAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/vm/ModifyScheduleReviewViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/vm/ModifyScheduleReviewViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/activity_modify_schedule_review.xml
Labels: 기능

#267 [#266] 관광지 상세보기 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/DetailActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailDisabilityRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailInfoRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailReviewRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/ReviewListRVAdapter.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/customview/CustomPageIndicator.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/main/fragment/HomeMainFragment.kt
  DaOnGil/app/src/main/res/drawable-night/detail_address_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_call_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_link_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_parking_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_road_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable-night/detail_wheelchair_icon.xml
  DaOnGil/app/src/main/res/drawable-night/review_report_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_address_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_call_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_elderly_people_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_hearing_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_infant_family_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_link_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_parking_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_physical_disability_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_road_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_visual_impairment_icon.xml
  DaOnGil/app/src/main/res/drawable/detail_wheelchair_icon.xml
  DaOnGil/app/src/main/res/drawable/review_report_icon.xml
  DaOnGil/app/src/main/res/layout/activity_detail.xml
  DaOnGil/app/src/main/res/layout/activity_review_list.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_big.xml
  DaOnGil/app/src/main/res/layout/item_detail_review_small.xml
  DaOnGil/app/src/main/res/layout/item_detail_service_info.xml
  DaOnGil/app/src/main/res/layout/item_review_big_image.xml
  DaOnGil/app/src/main/res/values-night/colors.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: UI, 리팩토링

#270 [#269] 후기 작성하기 UI 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/repository/PlanRepositoryImpl.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/repository/PlanRepository.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/WriteReviewActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/schedulereview/WriteScheduleReviewActivity.kt
  DaOnGil/app/src/main/res/layout/activity_write_review.xml
Labels: UI, 리팩토링

#274 [#273] 관심유형 선택 리팩토링
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/fragment/ConcernTypeSelectFragment.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/ConcernTypeSelectViewModel.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/login/vm/ConcernTypeSelectViewModelFactory.kt
  DaOnGil/app/src/main/res/layout/fragment_concern_type_select.xml
  DaOnGil/app/src/main/res/navigation/login_navigation_graph.xml
Labels: 리팩토링

#275 [#272] 홈 메인 고대비버전 디자인 수정
  DaOnGil/app/src/main/res/drawable-night/item_gradation_big.xml
  DaOnGil/app/src/main/res/layout/item_tourist_recommend.xml
  DaOnGil/app/src/main/res/values/colors.xml
Labels: UI, 리팩토링

#277 [#276] 북마크 버튼 위치 수정
  DaOnGil/app/src/main/res/layout/activity_detail.xml
Labels: 버그, UI

#279 [#278] 후기 데이터 구조 수정
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/DetailPlaceGuestResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailPlaceGuest/ReviewGuestRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/DetailPlaceResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/detailplace/ReviewRes.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/placeReview/Data.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/data/dto/remote/response/placeReview/PlaceReviewResponse.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/PlaceReviewInfo.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/domain/model/Review.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/ReviewListActivity.kt
  DaOnGil/app/src/main/java/kr/tekit/lion/daongil/presentation/home/adapter/DetailReviewRVAdapter.kt
Labels: 리팩토링
